Don't create CPU FlexAttention tests if CPU doesn't support it
Multiple tests will fail with
> torch._inductor.exc.InductorError: LoweringException: NotImplementedError: torch.compile on current platform is not supported for CPU.

This happens when CUDA support is available but the CPU doesn't support
FlexAttention (e.g. missing AVX2).

Also reduce duplication in the `*_SUPPORTED` and `TEST_ON_*` constants.