Skip tests using DynamoDistributedSingleProcTestCase without CUDA
When CUDA is not available `c10d.init_process_group("nccl"...)` will
fail with
> RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

Hence add a corresponding skip marker to the classes deriving from it
next to the `requires_nccl` marker.