[PT2][Optimus][Reliability]Fix a bug in gradients computation for runtime numeric check (#118105)
Summary:

We observed the following error when launch e2e AFOC model test
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```
f524190245

Test Plan:
'training_platform:c640e3f93574472da8894d9a0365f6a0'

f524376722
P1086047304

Differential Revision: D53011463