skip embedding_bag since its backward is not compatible to cudagraph
Summary:
Work around that the bwd of embedding_bag doesn't work with cudagraph with the following error:

RuntimeError: unique_by_key: failed to synchronize: cudaErrorStreamCaptureUnsupported: operation not permitted when stream is capturing

and then cuda memory error

Differential Revision: D40625081

fbshipit-source-id: 2c273a72da908f696cb2f3564732cf2f8aa8fc00