better error message fix
Summary:
A user had a problem with fx-scripting and the error message can be improved.

Error was shown as:

RuntimeError: Keys for dictionaries used as an argument cannot contain a Node. Got key: {k}

which is obvious not quite helpful.

Test Plan:
Test in a notebook:
{F778667593}

Reviewed By: xunnanxu, SherlockNoMad

Differential Revision: D40157518

fbshipit-source-id: 43b3f66390262a9d52bab7365863cd3e7b783f12