Fix warnings on s390x
In file included from /home/user/pytorch/aten/src/ATen/cpu/vec/vec256/vec256.h:26,
                 from /home/user/pytorch/aten/src/ATen/cpu/vec/vec.h:6,
                 from /home/user/pytorch/aten/src/ATen/native/cpu/Loops.h:37,
                 from /home/user/pytorch/aten/src/ATen/native/cpu/spherical_bessel_j0.cpp:8,
                 from /home/user/pytorch/build/aten/src/ATen/native/cpu/spherical_bessel_j0.cpp.ZVECTOR.cpp:1:
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h: In instantiation of ‘at::vec::ZVECTOR::Vectorized<T> at::vec::ZVECTOR::Vectorized<T, typename std::enable_if<is_zarch_implemented<T>(),
 void>::type>::swapped() const [with U = double; typename std::enable_if<std::is_same<U, double>::value, int>::type <anonymous> = 0; T = double; typename std::enable_if<is_zarch_implemented<T>(), void>::ty
pe = void]’:
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2723:1:   required from here
 2653 |     Vectorized<typex>::vinner_type vx_swapped = a.vec().swapped();                                         \
      |                                                 ~~~~~~~~~~~~~~~^~
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:1193:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 1193 |     vtype v0 = vec_permi(_vec0, _vec0, 2);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:1194:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 1194 |     vtype v1 = vec_permi(_vec1, _vec1, 2);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h: In instantiation of ‘static typename at::vec::ZVECTOR::Vectorized<T>::vinner_type at::vec::ZVECTOR::Vectorized<T, typename std::enable_if<is_zarch_implemented_complex<T>(), void>::type>::real_neg(const typename at::vec::ZVECTOR::Vectorized<T>::vinner_type&) [with U = c10::complex<double>; typename std::enable_if<std::is_same<U, c10::complex<double> >::value, int>::type <anonymous> = 0; T = c10::complex<double>; typename at::vec::ZVECTOR::Vectorized<T>::vinner_type = at::vec::ZVECTOR::Vectorized<double>]’:
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2723:1:   required from here
 2671 |     dc2 = Vectorized<typex>::real_neg(dc2);                     /* -d/|c,d|        c/sc */                 \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2422:24: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2422 |     auto v0 = vec_permi(a_neg.vec0(), a.vec0(), 1);
      |                        ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2423:24: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2423 |     auto v1 = vec_permi(a_neg.vec1(), a.vec1(), 1);
      |                        ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h: In instantiation of ‘std::pair<at::vec::ZVECTOR::Vectorized<T>, at::vec::ZVECTOR::Vectorized<T> > at::vec::ZVECTOR::inner_interleave2(const Vectorized<T>&, const Vectorized<T>&) [with T = double; typename std::enable_if<(sizeof (U) == 8), int>::type <anonymous> = 0]’:
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2834:35:   required from here
 2834 |   return inner_interleave2<double>(a, b);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2735:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2735 |   vtype ab00 = vec_permi(a.vec0(), b.vec0(), 0);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2736:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2736 |   vtype ab11 = vec_permi(a.vec0(), b.vec0(), 3);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2737:27: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2737 |   vtype ab2_00 = vec_permi(a.vec1(), b.vec1(), 0);
      |                           ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2738:27: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2738 |   vtype ab2_11 = vec_permi(a.vec1(), b.vec1(), 3);
      |                           ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h: In instantiation of ‘std::pair<at::vec::ZVECTOR::Vectorized<T>, at::vec::ZVECTOR::Vectorized<T> > at::vec::ZVECTOR::inner_deinterleave2(const Vectorized<T>&, const Vectorized<T>&) [with T = double; typename std::enable_if<(sizeof (U) == 8), int>::type <anonymous> = 0]’:
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2861:37:   required from here
 2861 |   return inner_deinterleave2<double>(a, b);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2753:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2753 |   vtype aa01 = vec_permi(a.vec0(), a.vec1(), 0);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2754:25: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2754 |   vtype aa23 = vec_permi(b.vec0(), b.vec1(), 0);
      |                         ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2756:26: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2756 |   vtype bb_01 = vec_permi(a.vec0(), a.vec1(), 3);
      |                          ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:2757:26: error: builtin ‘__vector(4) int __builtin_s390_vec_permi(__vector(4) int, __vector(4) int, int)’ is deprecated [-Werror]
 2757 |   vtype bb_23 = vec_permi(b.vec0(), b.vec1(), 3);
      |                          ^
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:1714:21: error: ‘at::vec::ZVECTOR::Vectorized<T> at::vec::ZVECTOR::{anonymous}::pack(const at::vec::ZVECTOR::Vectorized<T>&, const at::vec::ZVECTOR::Vectorized<T>&) [with T = short int; V = unsigned char]’ defined but not used [-Werror=unused-function]
 1714 | Vectorized<uint8_t> pack(
      |                     ^~~~
/home/user/pytorch/aten/src/ATen/cpu/vec/vec256/zarch/vec256_zarch.h:1689:53: error: ‘std::pair<at::vec::ZVECTOR::Vectorized<T>, at::vec::ZVECTOR::Vectorized<T> > at::vec::ZVECTOR::{anonymous}::unpack(const at::vec::ZVECTOR::Vectorized<T>&) [with T = unsigned char; V = short int]’ defined but not used [-Werror=unused-function]
 1689 | std::pair<Vectorized<int16_t>, Vectorized<int16_t>> unpack<uint8_t, int16_t>(
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/user/pytorch/aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp:159:33: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  159 |               for (int i = 0; i < Vec::float_num_vecs(); ++i) {
      |                               ~~^~~~~~~~~~~~~~~~~~~~~~~